# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sched.v1 import sched_pb2 as sched_dot_v1_dot_sched__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sched/v1/sched_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerStub:
    """Scheduler is the job queue's client-facing API. Producers Submit jobs;
    workers Claim them under a lease, Heartbeat to keep the lease, and
    Complete or Fail them. Every worker-side mutation carries the fencing
    token (gen) the worker was given at Claim time; a stale token is refused
    with FailedPrecondition, which is how a worker that was paused past its
    lease finds out its work has been given to someone else.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Submit = channel.unary_unary(
                '/sched.v1.Scheduler/Submit',
                request_serializer=sched_dot_v1_dot_sched__pb2.SubmitRequest.SerializeToString,
                response_deserializer=sched_dot_v1_dot_sched__pb2.SubmitResponse.FromString,
                _registered_method=True)
        self.Claim = channel.unary_unary(
                '/sched.v1.Scheduler/Claim',
                request_serializer=sched_dot_v1_dot_sched__pb2.ClaimRequest.SerializeToString,
                response_deserializer=sched_dot_v1_dot_sched__pb2.ClaimResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/sched.v1.Scheduler/Heartbeat',
                request_serializer=sched_dot_v1_dot_sched__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=sched_dot_v1_dot_sched__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Complete = channel.unary_unary(
                '/sched.v1.Scheduler/Complete',
                request_serializer=sched_dot_v1_dot_sched__pb2.CompleteRequest.SerializeToString,
                response_deserializer=sched_dot_v1_dot_sched__pb2.CompleteResponse.FromString,
                _registered_method=True)
        self.Fail = channel.unary_unary(
                '/sched.v1.Scheduler/Fail',
                request_serializer=sched_dot_v1_dot_sched__pb2.FailRequest.SerializeToString,
                response_deserializer=sched_dot_v1_dot_sched__pb2.FailResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/sched.v1.Scheduler/Status',
                request_serializer=sched_dot_v1_dot_sched__pb2.StatusRequest.SerializeToString,
                response_deserializer=sched_dot_v1_dot_sched__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/sched.v1.Scheduler/Stats',
                request_serializer=sched_dot_v1_dot_sched__pb2.StatsRequest.SerializeToString,
                response_deserializer=sched_dot_v1_dot_sched__pb2.StatsResponse.FromString,
                _registered_method=True)


class SchedulerServicer:
    """Scheduler is the job queue's client-facing API. Producers Submit jobs;
    workers Claim them under a lease, Heartbeat to keep the lease, and
    Complete or Fail them. Every worker-side mutation carries the fencing
    token (gen) the worker was given at Claim time; a stale token is refused
    with FailedPrecondition, which is how a worker that was paused past its
    lease finds out its work has been given to someone else.
    """

    def Submit(self, request, context):
        """Submit enqueues a job. ResourceExhausted (with retry_after_ms in the
        error details/message) when the queue is at capacity: shed load at
        admission, do not accept work you cannot start.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Claim(self, request, context):
        """Claim hands the caller the oldest runnable job under a fresh lease.
        found=false when nothing is runnable; poll again after a backoff.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat extends the lease. FailedPrecondition if gen is stale.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """Complete records the result and finishes the job. FailedPrecondition
        if gen is stale: someone else owns the job now, discard your result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fail(self, request, context):
        """Fail reports an attempt failed; the job is requeued (gen advances) or
        marked FAILED once attempts are exhausted. FailedPrecondition if stale.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Status reads a job record.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Stats reports queue depth.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=sched_dot_v1_dot_sched__pb2.SubmitRequest.FromString,
                    response_serializer=sched_dot_v1_dot_sched__pb2.SubmitResponse.SerializeToString,
            ),
            'Claim': grpc.unary_unary_rpc_method_handler(
                    servicer.Claim,
                    request_deserializer=sched_dot_v1_dot_sched__pb2.ClaimRequest.FromString,
                    response_serializer=sched_dot_v1_dot_sched__pb2.ClaimResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=sched_dot_v1_dot_sched__pb2.HeartbeatRequest.FromString,
                    response_serializer=sched_dot_v1_dot_sched__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=sched_dot_v1_dot_sched__pb2.CompleteRequest.FromString,
                    response_serializer=sched_dot_v1_dot_sched__pb2.CompleteResponse.SerializeToString,
            ),
            'Fail': grpc.unary_unary_rpc_method_handler(
                    servicer.Fail,
                    request_deserializer=sched_dot_v1_dot_sched__pb2.FailRequest.FromString,
                    response_serializer=sched_dot_v1_dot_sched__pb2.FailResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=sched_dot_v1_dot_sched__pb2.StatusRequest.FromString,
                    response_serializer=sched_dot_v1_dot_sched__pb2.StatusResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=sched_dot_v1_dot_sched__pb2.StatsRequest.FromString,
                    response_serializer=sched_dot_v1_dot_sched__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sched.v1.Scheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sched.v1.Scheduler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Scheduler:
    """Scheduler is the job queue's client-facing API. Producers Submit jobs;
    workers Claim them under a lease, Heartbeat to keep the lease, and
    Complete or Fail them. Every worker-side mutation carries the fencing
    token (gen) the worker was given at Claim time; a stale token is refused
    with FailedPrecondition, which is how a worker that was paused past its
    lease finds out its work has been given to someone else.
    """

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sched.v1.Scheduler/Submit',
            sched_dot_v1_dot_sched__pb2.SubmitRequest.SerializeToString,
            sched_dot_v1_dot_sched__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Claim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sched.v1.Scheduler/Claim',
            sched_dot_v1_dot_sched__pb2.ClaimRequest.SerializeToString,
            sched_dot_v1_dot_sched__pb2.ClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sched.v1.Scheduler/Heartbeat',
            sched_dot_v1_dot_sched__pb2.HeartbeatRequest.SerializeToString,
            sched_dot_v1_dot_sched__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sched.v1.Scheduler/Complete',
            sched_dot_v1_dot_sched__pb2.CompleteRequest.SerializeToString,
            sched_dot_v1_dot_sched__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sched.v1.Scheduler/Fail',
            sched_dot_v1_dot_sched__pb2.FailRequest.SerializeToString,
            sched_dot_v1_dot_sched__pb2.FailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sched.v1.Scheduler/Status',
            sched_dot_v1_dot_sched__pb2.StatusRequest.SerializeToString,
            sched_dot_v1_dot_sched__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sched.v1.Scheduler/Stats',
            sched_dot_v1_dot_sched__pb2.StatsRequest.SerializeToString,
            sched_dot_v1_dot_sched__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
