# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway/v1/gateway.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'gateway/v1/gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18gateway/v1/gateway.proto\x12\ngateway.v1\"W\n\x0fGenerateRequest\x12\x0e\n\x06tenant\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x12\n\nmax_tokens\x18\x03 \x01(\x05\x12\x10\n\x08no_cache\x18\x04 \x01(\x08\"\xcb\x01\n\x05Token\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x12\x15\n\rfinish_reason\x18\x04 \x01(\t\x12\x0e\n\x06\x63\x61\x63hed\x18\x05 \x01(\x08\x12\x0e\n\x06worker\x18\x06 \x01(\t\x12\x0e\n\x06hedged\x18\x07 \x01(\x08\x12\x11\n\thedge_won\x18\x08 \x01(\x08\x12\x0f\n\x07ttft_ms\x18\t \x01(\x03\x12\x18\n\x10prefix_cache_hit\x18\n \x01(\x08\x12\x12\n\nprefill_ms\x18\x0b \x01(\x03\"k\n\x15RegisterWorkerRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\x12\x10\n\x08inflight\x18\x03 \x01(\x05\x12\x10\n\x08lease_ms\x18\x04 \x01(\x03\x12\r\n\x05model\x18\x05 \x01(\t\"0\n\x16RegisterWorkerResponse\x12\x16\n\x0elease_until_ms\x18\x01 \x01(\x03\"\x0e\n\x0cStatsRequest\"\xa5\x02\n\rStatsResponse\x12\x10\n\x08requests\x18\x01 \x01(\x04\x12\x14\n\x0crate_limited\x18\x02 \x01(\x04\x12\x12\n\ncache_hits\x18\x03 \x01(\x04\x12\x17\n\x0fhedges_launched\x18\x04 \x01(\x04\x12\x12\n\nhedges_won\x18\x05 \x01(\x04\x12\x11\n\tcancelled\x18\x06 \x01(\x04\x12\x15\n\rworker_errors\x18\x07 \x01(\x04\x12:\n\trouted_to\x18\x08 \x03(\x0b\x32\'.gateway.v1.StatsResponse.RoutedToEntry\x12\x14\n\x0clive_workers\x18\t \x01(\x05\x1a/\n\rRoutedToEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\x32\xde\x01\n\x07Gateway\x12<\n\x08Generate\x12\x1b.gateway.v1.GenerateRequest\x1a\x11.gateway.v1.Token0\x01\x12W\n\x0eRegisterWorker\x12!.gateway.v1.RegisterWorkerRequest\x1a\".gateway.v1.RegisterWorkerResponse\x12<\n\x05Stats\x12\x18.gateway.v1.StatsRequest\x1a\x19.gateway.v1.StatsResponseB\x1fZ\x1d\x64sys/gen/gateway/v1;gatewayv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway.v1.gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035dsys/gen/gateway/v1;gatewayv1'
  _globals['_STATSRESPONSE_ROUTEDTOENTRY']._loaded_options = None
  _globals['_STATSRESPONSE_ROUTEDTOENTRY']._serialized_options = b'8\001'
  _globals['_GENERATEREQUEST']._serialized_start=40
  _globals['_GENERATEREQUEST']._serialized_end=127
  _globals['_TOKEN']._serialized_start=130
  _globals['_TOKEN']._serialized_end=333
  _globals['_REGISTERWORKERREQUEST']._serialized_start=335
  _globals['_REGISTERWORKERREQUEST']._serialized_end=442
  _globals['_REGISTERWORKERRESPONSE']._serialized_start=444
  _globals['_REGISTERWORKERRESPONSE']._serialized_end=492
  _globals['_STATSREQUEST']._serialized_start=494
  _globals['_STATSREQUEST']._serialized_end=508
  _globals['_STATSRESPONSE']._serialized_start=511
  _globals['_STATSRESPONSE']._serialized_end=804
  _globals['_STATSRESPONSE_ROUTEDTOENTRY']._serialized_start=757
  _globals['_STATSRESPONSE_ROUTEDTOENTRY']._serialized_end=804
  _globals['_GATEWAY']._serialized_start=807
  _globals['_GATEWAY']._serialized_end=1029
# @@protoc_insertion_point(module_scope)
