# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gateway.v1 import gateway_pb2 as gateway_dot_v1_dot_gateway__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gateway/v1/gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayStub:
    """Gateway is the CLIENT-facing inference API. Every request passes, in
    order, through: per-tenant distributed rate limiting (token bucket in the
    KV), the semantic cache, prefix-aware routing to a worker, and hedging
    for tail latency. Tokens stream back; cancelling the stream cancels the
    worker.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/gateway.v1.Gateway/Generate',
                request_serializer=gateway_dot_v1_dot_gateway__pb2.GenerateRequest.SerializeToString,
                response_deserializer=gateway_dot_v1_dot_gateway__pb2.Token.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/gateway.v1.Gateway/RegisterWorker',
                request_serializer=gateway_dot_v1_dot_gateway__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=gateway_dot_v1_dot_gateway__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/gateway.v1.Gateway/Stats',
                request_serializer=gateway_dot_v1_dot_gateway__pb2.StatsRequest.SerializeToString,
                response_deserializer=gateway_dot_v1_dot_gateway__pb2.StatsResponse.FromString,
                _registered_method=True)


class GatewayServicer:
    """Gateway is the CLIENT-facing inference API. Every request passes, in
    order, through: per-tenant distributed rate limiting (token bucket in the
    KV), the semantic cache, prefix-aware routing to a worker, and hedging
    for tail latency. Tokens stream back; cancelling the stream cancels the
    worker.
    """

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """RegisterWorker is called by inference workers periodically (a lease):
        the gateway records them in the shared registry so every gateway
        replica routes over the same live set.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=gateway_dot_v1_dot_gateway__pb2.GenerateRequest.FromString,
                    response_serializer=gateway_dot_v1_dot_gateway__pb2.Token.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=gateway_dot_v1_dot_gateway__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=gateway_dot_v1_dot_gateway__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=gateway_dot_v1_dot_gateway__pb2.StatsRequest.FromString,
                    response_serializer=gateway_dot_v1_dot_gateway__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gateway.v1.Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gateway.v1.Gateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Gateway:
    """Gateway is the CLIENT-facing inference API. Every request passes, in
    order, through: per-tenant distributed rate limiting (token bucket in the
    KV), the semantic cache, prefix-aware routing to a worker, and hedging
    for tail latency. Tokens stream back; cancelling the stream cancels the
    worker.
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gateway.v1.Gateway/Generate',
            gateway_dot_v1_dot_gateway__pb2.GenerateRequest.SerializeToString,
            gateway_dot_v1_dot_gateway__pb2.Token.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.Gateway/RegisterWorker',
            gateway_dot_v1_dot_gateway__pb2.RegisterWorkerRequest.SerializeToString,
            gateway_dot_v1_dot_gateway__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.Gateway/Stats',
            gateway_dot_v1_dot_gateway__pb2.StatsRequest.SerializeToString,
            gateway_dot_v1_dot_gateway__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
