# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infer/v1/infer.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'infer/v1/infer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14infer/v1/infer.proto\x12\x08infer.v1\"Y\n\x0fGenerateRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06tenant\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x03 \x01(\t\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\"\x94\x01\n\x05Token\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x12\x15\n\rfinish_reason\x18\x04 \x01(\t\x12\x12\n\nprefill_ms\x18\x05 \x01(\x03\x12\x18\n\x10prefix_cache_hit\x18\x06 \x01(\x08\x12\x1b\n\x13\x63\x61\x63hed_prefix_chars\x18\x07 \x01(\x05\"\x0f\n\rHealthRequest\"D\n\x0eHealthResponse\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x10\n\x08inflight\x18\x02 \x01(\x05\x12\r\n\x05model\x18\x03 \x01(\t2\x82\x01\n\tInference\x12\x38\n\x08Generate\x12\x19.infer.v1.GenerateRequest\x1a\x0f.infer.v1.Token0\x01\x12;\n\x06Health\x12\x17.infer.v1.HealthRequest\x1a\x18.infer.v1.HealthResponseB\x1bZ\x19\x64sys/gen/infer/v1;inferv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infer.v1.infer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031dsys/gen/infer/v1;inferv1'
  _globals['_GENERATEREQUEST']._serialized_start=34
  _globals['_GENERATEREQUEST']._serialized_end=123
  _globals['_TOKEN']._serialized_start=126
  _globals['_TOKEN']._serialized_end=274
  _globals['_HEALTHREQUEST']._serialized_start=276
  _globals['_HEALTHREQUEST']._serialized_end=291
  _globals['_HEALTHRESPONSE']._serialized_start=293
  _globals['_HEALTHRESPONSE']._serialized_end=361
  _globals['_INFERENCE']._serialized_start=364
  _globals['_INFERENCE']._serialized_end=494
# @@protoc_insertion_point(module_scope)
