# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from infer.v1 import infer_pb2 as infer_dot_v1_dot_infer__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in infer/v1/infer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceStub:
    """Inference is the WORKER-facing API: what the gateway speaks to an
    inference worker (a Python process hosting a model, or the Go mock used
    in tests and benchmarks). Clients never call this directly; they call the
    gateway, which adds rate limiting, caching, routing and hedging in front.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/infer.v1.Inference/Generate',
                request_serializer=infer_dot_v1_dot_infer__pb2.GenerateRequest.SerializeToString,
                response_deserializer=infer_dot_v1_dot_infer__pb2.Token.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/infer.v1.Inference/Health',
                request_serializer=infer_dot_v1_dot_infer__pb2.HealthRequest.SerializeToString,
                response_deserializer=infer_dot_v1_dot_infer__pb2.HealthResponse.FromString,
                _registered_method=True)


class InferenceServicer:
    """Inference is the WORKER-facing API: what the gateway speaks to an
    inference worker (a Python process hosting a model, or the Go mock used
    in tests and benchmarks). Clients never call this directly; they call the
    gateway, which adds rate limiting, caching, routing and hedging in front.
    """

    def Generate(self, request, context):
        """Generate streams tokens for one prompt. Cancelling the stream (client
        context cancel) must stop generation on the worker: tokens after a
        cancel are wasted GPU time, and with hedging (gateway) the loser of a
        hedge race is cancelled precisely so it stops burning compute.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health reports current load so the gateway can route around a busy
        worker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=infer_dot_v1_dot_infer__pb2.GenerateRequest.FromString,
                    response_serializer=infer_dot_v1_dot_infer__pb2.Token.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=infer_dot_v1_dot_infer__pb2.HealthRequest.FromString,
                    response_serializer=infer_dot_v1_dot_infer__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'infer.v1.Inference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('infer.v1.Inference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inference:
    """Inference is the WORKER-facing API: what the gateway speaks to an
    inference worker (a Python process hosting a model, or the Go mock used
    in tests and benchmarks). Clients never call this directly; they call the
    gateway, which adds rate limiting, caching, routing and hedging in front.
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/infer.v1.Inference/Generate',
            infer_dot_v1_dot_infer__pb2.GenerateRequest.SerializeToString,
            infer_dot_v1_dot_infer__pb2.Token.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infer.v1.Inference/Health',
            infer_dot_v1_dot_infer__pb2.HealthRequest.SerializeToString,
            infer_dot_v1_dot_infer__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
