# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv/v1/kv.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'kv/v1/kv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekv/v1/kv.proto\x12\x05kv.v1\"4\n\x0bRequestMeta\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\x04\"J\n\nPutRequest\x12 \n\x04meta\x18\x01 \x01(\x0b\x32\x12.kv.v1.RequestMeta\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x0c\"\r\n\x0bPutResponse\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\">\n\rDeleteRequest\x12 \n\x04meta\x18\x01 \x01(\x0b\x32\x12.kv.v1.RequestMeta\x12\x0b\n\x03key\x18\x02 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07\x65xisted\x18\x01 \x01(\x08\"s\n\nCASRequest\x12 \n\x04meta\x18\x01 \x01(\x0b\x32\x12.kv.v1.RequestMeta\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x10\n\x08\x65xpected\x18\x03 \x01(\x0c\x12\x15\n\rexpect_absent\x18\x04 \x01(\x08\x12\r\n\x05value\x18\x05 \x01(\x0c\"/\n\x0b\x43\x41SResponse\x12\x0f\n\x07swapped\x18\x01 \x01(\x08\x12\x0f\n\x07\x63urrent\x18\x02 \x01(\x0c\"\x88\x01\n\x08LogEntry\x12\x15\n\x02op\x18\x01 \x01(\x0e\x32\t.kv.v1.Op\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x0c\x12\x10\n\x08\x65xpected\x18\x04 \x01(\x0c\x12\x15\n\rexpect_absent\x18\x05 \x01(\x08\x12 \n\x04meta\x18\x06 \x01(\x0b\x32\x12.kv.v1.RequestMeta*K\n\x02Op\x12\x12\n\x0eOP_UNSPECIFIED\x10\x00\x12\n\n\x06OP_PUT\x10\x01\x12\r\n\tOP_DELETE\x10\x02\x12\n\n\x06OP_CAS\x10\x03\x12\n\n\x06OP_GET\x10\x04\x32\xd0\x01\n\x02KV\x12,\n\x03Put\x12\x11.kv.v1.PutRequest\x1a\x12.kv.v1.PutResponse\x12,\n\x03Get\x12\x11.kv.v1.GetRequest\x1a\x12.kv.v1.GetResponse\x12\x35\n\x06\x44\x65lete\x12\x14.kv.v1.DeleteRequest\x1a\x15.kv.v1.DeleteResponse\x12\x37\n\x0e\x43ompareAndSwap\x12\x11.kv.v1.CASRequest\x1a\x12.kv.v1.CASResponseB\x15Z\x13\x64sys/gen/kv/v1;kvv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv.v1.kv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023dsys/gen/kv/v1;kvv1'
  _globals['_OP']._serialized_start=646
  _globals['_OP']._serialized_end=721
  _globals['_REQUESTMETA']._serialized_start=25
  _globals['_REQUESTMETA']._serialized_end=77
  _globals['_PUTREQUEST']._serialized_start=79
  _globals['_PUTREQUEST']._serialized_end=153
  _globals['_PUTRESPONSE']._serialized_start=155
  _globals['_PUTRESPONSE']._serialized_end=168
  _globals['_GETREQUEST']._serialized_start=170
  _globals['_GETREQUEST']._serialized_end=195
  _globals['_GETRESPONSE']._serialized_start=197
  _globals['_GETRESPONSE']._serialized_end=240
  _globals['_DELETEREQUEST']._serialized_start=242
  _globals['_DELETEREQUEST']._serialized_end=304
  _globals['_DELETERESPONSE']._serialized_start=306
  _globals['_DELETERESPONSE']._serialized_end=339
  _globals['_CASREQUEST']._serialized_start=341
  _globals['_CASREQUEST']._serialized_end=456
  _globals['_CASRESPONSE']._serialized_start=458
  _globals['_CASRESPONSE']._serialized_end=505
  _globals['_LOGENTRY']._serialized_start=508
  _globals['_LOGENTRY']._serialized_end=644
  _globals['_KV']._serialized_start=724
  _globals['_KV']._serialized_end=932
# @@protoc_insertion_point(module_scope)
