# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kv.v1 import kv_pb2 as kv_dot_v1_dot_kv__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kv/v1/kv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KVStub:
    """KV is the client-facing API of the store.

    Every mutating request carries RequestMeta so the server can detect a
    retried request and return the original result instead of applying the
    mutation twice. This is how "exactly-once" is actually built: at-least-once
    delivery (client retries) + server-side deduplication.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/kv.v1.KV/Put',
                request_serializer=kv_dot_v1_dot_kv__pb2.PutRequest.SerializeToString,
                response_deserializer=kv_dot_v1_dot_kv__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/kv.v1.KV/Get',
                request_serializer=kv_dot_v1_dot_kv__pb2.GetRequest.SerializeToString,
                response_deserializer=kv_dot_v1_dot_kv__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/kv.v1.KV/Delete',
                request_serializer=kv_dot_v1_dot_kv__pb2.DeleteRequest.SerializeToString,
                response_deserializer=kv_dot_v1_dot_kv__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.CompareAndSwap = channel.unary_unary(
                '/kv.v1.KV/CompareAndSwap',
                request_serializer=kv_dot_v1_dot_kv__pb2.CASRequest.SerializeToString,
                response_deserializer=kv_dot_v1_dot_kv__pb2.CASResponse.FromString,
                _registered_method=True)


class KVServicer:
    """KV is the client-facing API of the store.

    Every mutating request carries RequestMeta so the server can detect a
    retried request and return the original result instead of applying the
    mutation twice. This is how "exactly-once" is actually built: at-least-once
    delivery (client retries) + server-side deduplication.
    """

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompareAndSwap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=kv_dot_v1_dot_kv__pb2.PutRequest.FromString,
                    response_serializer=kv_dot_v1_dot_kv__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=kv_dot_v1_dot_kv__pb2.GetRequest.FromString,
                    response_serializer=kv_dot_v1_dot_kv__pb2.GetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=kv_dot_v1_dot_kv__pb2.DeleteRequest.FromString,
                    response_serializer=kv_dot_v1_dot_kv__pb2.DeleteResponse.SerializeToString,
            ),
            'CompareAndSwap': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareAndSwap,
                    request_deserializer=kv_dot_v1_dot_kv__pb2.CASRequest.FromString,
                    response_serializer=kv_dot_v1_dot_kv__pb2.CASResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kv.v1.KV', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kv.v1.KV', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KV:
    """KV is the client-facing API of the store.

    Every mutating request carries RequestMeta so the server can detect a
    retried request and return the original result instead of applying the
    mutation twice. This is how "exactly-once" is actually built: at-least-once
    delivery (client retries) + server-side deduplication.
    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.v1.KV/Put',
            kv_dot_v1_dot_kv__pb2.PutRequest.SerializeToString,
            kv_dot_v1_dot_kv__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.v1.KV/Get',
            kv_dot_v1_dot_kv__pb2.GetRequest.SerializeToString,
            kv_dot_v1_dot_kv__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.v1.KV/Delete',
            kv_dot_v1_dot_kv__pb2.DeleteRequest.SerializeToString,
            kv_dot_v1_dot_kv__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompareAndSwap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.v1.KV/CompareAndSwap',
            kv_dot_v1_dot_kv__pb2.CASRequest.SerializeToString,
            kv_dot_v1_dot_kv__pb2.CASResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
